
var stray_birds_json =
  {
    "1": "\r\n夏天的飞鸟，飞到我的窗前唱歌，又飞去了。\r\n秋天的黄叶，它们没有什么可唱，只叹息一声，飞落在那里。\r\nStray birds of summer come to my window to sing and fly away.\r\nAnd yellow leaves of autumn, which have no songs, flutter and fall there with a sigh.",
    "2": "\r\n世界上的一队小小的漂泊者呀，请留下你们的足印在我的文字里。\r\nO Troupe of little vagrants of the world, leave your footprints in my words.",
    "3": "\r\n世界对着它的爱人，把它浩翰的面具揭下了。\r\n它变小了，小如一首歌，小如一回永恒的接吻。\r\nThe world puts off its mask of vastness to its lover.\r\nIt becomes small as one song, as one kiss of the eternal.",
    "4": "\r\n是大地的泪点，使她的微笑保持着青春不谢。\r\nIt is the tears of the earth that keep her smiles in bloom.",
    "5": "\r\n无垠的沙漠热烈追求一叶绿草的爱，她摇摇头笑着飞开了。\r\nThe mighty desert is burning for the love of a blade of grass who shakes her head and laughs and flies away.",
    "6": "\r\n如果你因失去了太阳而流泪，那么你也将失去群星了。\r\nIf you shed tears when you miss the sun, you also miss the stars.",
    "7": "\r\n跳舞着的流水呀，在你途中的泥沙，要求你的歌声，你的流动呢。你肯挟瘸足的泥沙而俱下么？\r\nThe sands in your way beg for your song and your movement, dancing water. Will you carry the burden of their lameness?",
    "8": "\r\n她的热切的脸，如夜雨似的，搅扰着我的梦魂。\r\nHer wishful face haunts my dreams like the rain at night.",
    "9": "\r\n有一次，我们梦见大家都是不相识的。\r\n我们醒了，却知道我们原是相亲相爱的。\r\nOnce we dreamt that we were strangers.\r\nWe wake up to find that we were dear to each other.",
    "10": "\r\n忧思在我的心里平静下去，正如暮色降临在寂静的山林中。\r\nSorrow is hushed into peace in my heart like the evening among the silent trees.",
    "11": "\r\n有些看不见的手，如懒懒的微风似的，正在我的心上奏着\r\n潺潺的乐声。\r\nSome unseen fingers, like an idle breeze, are playing upon my heart the music of the ripples.",
    "12": "\r\n“海水呀，你说的是什么？”\r\n“是永恒的疑问。”\r\n“天空呀，你回答的话是什么？”\r\n“是永恒的沉默。”\r\nWhat language is thine, O sea?\r\nThe language of eternal question.\r\nWhat language is thy answer, O sky?\r\nThe language of eternal silence.",
    "13": "\r\n静静地听，我的心呀，听那世界的低语，这是它对你求爱的表示呀。\r\nListen, my heart, to the whispers of the world with which it makes love to you.",
    "14": "\r\n创造的神秘，有如夜间的黑暗－－是伟大的。而知识的幻影却不过如晨间之雾。\r\nThe mystery of creation is like the darkness of night--it is great.\r\nDelusions of knowledge are like the fog of the morning.",
    "15": "\r\n不要因为峭壁是高的，便让你的爱情坐在峭壁上。\r\nDo not seat your love upon a precipice because it is high.",
    "16": "\r\n我今晨坐在窗前，世界如一个路人似的，停留了一会，向我点点头又走过去了。\r\nI sit at my window this morning where the world like a passer-by stops for a moment, nods to me and goes.",
    "17": "\r\n这些微（风思），是树叶的簌簌之声呀；它们在我的心里欢悦地微语着。\r\nThese little thoughts are the rustle of leaves; they have their whisper of joy in my mind.",
    "18": "\r\n你看不见你自己，你所看见的只是你的影子。\r\nWhat you are you do not see, what you see is your shadow.",
    "19": "\r\n神呀，我的那些愿望真是愚傻呀，它们杂在你的歌声中喧叫着呢。\r\n让我只是静听着吧。\r\nMy wishes are fools, they shout across thy song, my Master.\r\nLet me but listen.",
    "20": "\r\n我不能选择那最好的。\r\n是那最好的选择我。\r\nI cannot choose the best.\r\nThe best chooses me.",
    "21": "\r\n那些把灯背在背上的人，把他们的影子投到了自己前面。\r\nThey throw their shadows before them who carry their lantern on their back.",
    "22": "\r\n我的存在，对我是一个永久的神奇，这就是生活。\r\nThat I exist is a perpetual surprise which is life.",
    "23": "\r\n“我们萧萧的树叶都有声响回答那风和雨。你是谁呢，那样的沉默着？”\r\n“我不过是一朵花。”\r\nWe, the rustling leaves, have a voice that answers the storms, but who are you so silent?\"\r\nI am a mere flower.",
    "24": "\r\n休息与工作的关系，正如眼睑与眼睛的关系。\r\nRest belongs to the work as the eyelids to the eyes.",
    "25": "\r\n人是一个初生的孩子，他的力量，就是生长的力量。\r\nMan is a born child; his power is the power of growth.",
    "26": "\r\n神希望我们酬答他，在于他送给我们的花朵，而不在于太阳和土地。\r\nGod expects answers for the flowers he sends us, not for the sun and the earth.",
    "27": "\r\n光明如一个裸体的孩子，快快活活地在绿叶当中游戏，它不知道人是会欺诈的。\r\nThe light that plays, like a naked child, among the green leaves happily knows not that man can lie.",
    "28": "\r\n啊，美呀，在爱中找你自己吧，不要到你镜子的谄谀去找寻。\r\nO Beauty, find thyself in love, not in the flattery of thy mirror.",
    "29": "\r\n我的心把她的波浪在世界的海岸上冲激着，以热泪在上边写着她的题记：\r\n“我爱你。”\r\nMy heart beats her waves at the shore of the world and writes upon it her signature in tears with the words, \"I love thee.\"",
    "30": "\r\n“月儿呀，你在等候什么呢？”\r\n“向我将让位给他的太阳致敬。”\r\nMoon, for what do you wait?\r\nTo salute the sun for whom I must make way.",
    "31": "\r\n绿树长到了我的窗前，仿佛是喑哑的大地发出的渴望的声音。\r\nThe trees come up to my window like the yearning voice of the dumb earth.",
    "32": "\r\n神自己的清晨，在他自己看来也是新奇的。\r\nHis own mornings are new surprises to God.",
    "33": "\r\n生命从世界得到资产，爱情使它得到价值。\r\nLife finds its wealth by the claims of the world, and its worth by the claims of love.",
    "34": "\r\n枯竭的河床，并不感谢它的过去。\r\nThe dry river-bed finds no thanks for its past.",
    "35": "\r\n鸟儿愿为一朵云。\r\n云儿愿为一只鸟。\r\nThe bird wishes it were a cloud.\r\nThe cloud wishes it were a bird.",
    "36": "\r\n瀑布歌唱道：“我得到自由时便有了歌声了。”\r\nThe waterfall sings, \"I find my song, when I find my freedom.\"",
    "37": "\r\n我说不出这心为什么那样默默地颓丧着。\r\n是为了它那不曾要求，不曾知道，不曾记得的小小的需要。\r\nI cannot tell why this heart languishes in silence.\r\nIt is for small needs it never asks, or knows or remembers.",
    "38": "\r\n妇人，你在料理家务的时候，你的手足歌唱着，正如山间的溪水歌唱着在\r\n小石中流过。\r\nWoman, when you move about in your household service your limbs sing like a hill stream among its pebbles.",
    "39": "\r\n当太阳横过西方的海面时，对着东方留下他的最后的敬礼。\r\nThe sun goes to cross the Western sea, leaving its last salutation to the East.",
    "40": "\r\n不要因为你自己没有胃口而去责备你的食物。\r\nDo not blame your food because you have no appetite.",
    "41": "\r\n群树如表示大地的愿望似的，踮起脚来向天空窥望。\r\nThe trees, like the longings of the earth, stand atiptoe to peep at the heaven.",
    "42": "\r\n你微微地笑着，不同我说什么话。而我觉得，为了这个，我已等待得久了。\r\nYou smiled and talked to me of nothing and I felt that for this I had been waiting long.",
    "43": "\r\n水里的游鱼是沉默的，陆地上的兽类是喧闹的，空中的飞鸟是歌唱着的。\r\n但是，人类却兼有海里的沉默，地上的喧闹与空中的音乐。\r\nThe fish in the water is silent, the animal on the earth is noisy, the bird in the air is singing.\r\nBut Man has in him the silence of the sea, the noise of the earth and the music of the air.",
    "44": "\r\n世界在踌躇之心的琴弦上跑过去，奏出忧郁的乐声。\r\nThe world rushes on over the strings of the lingering heart making the music of sadness.",
    "45": "\r\n他把他的刀剑当作他的上帝。\r\n当他的刀剑胜利的时候他自己却失败了。\r\nHe has made his weapons his gods.\r\nWhen his weapons win he is defeated himself.",
    "46": "\r\n神从创造中找到他自己。\r\nGod finds himself by creating.",
    "47": "\r\n阴影戴上她的面幕，秘密地，温顺地，用她的沉默的爱的脚步，跟在“光”后边。\r\nShadow, with her veil drawn, follows Light in secret meekness, with her silent steps of love.",
    "48": "\r\n群星不怕显得象萤火那样。\r\nThe stars are not afraid to appear like fireflies.",
    "49": "\r\n谢谢神，我不是一个权力的轮子，而是被压在这轮子下的活人之一。\r\nI thank thee that I am none of the wheels of power but I am one with the living creatures that are crushed by it.",
    "50": "\r\n心是尖锐的，不是宽博的，它执着在每一点上，却并不活动。\r\nThe mind, sharp but not broad, sticks at every point but does not move.",
    "51": "\r\n你的偶像委散在尘土中了，这可证明神的尘土比你的偶像还伟大。\r\nYour idol is shattered in the dust to prove that God's dust is greater than your idol.",
    "52": "\r\n人不能在他的历史中表现出他自己，他在历史中奋斗着露出头角。\r\nMan does not reveal himself in his history, he struggles up through it.",
    "53": "\r\n玻璃灯因为瓦灯叫它做表兄而责备瓦灯。但明月出来时，玻璃\r\n灯却温和地微笑着，叫明月为－－－“我亲爱的，亲爱的姐姐。”\r\nWhile the glass lamp rebukes the earthen for calling it cousin the moon rises, and the glass lamp, with a bland smile, calls her, ---My dear, dear sister.",
    "54": "\r\n我们如海鸥之与波涛相遇似地，遇见了，走近了。海鸥飞去，波涛滚滚地流\r\n开，我们也分别了。\r\nLike the meeting of the seagulls and the waves we meet and come near.\r\nThe seagulls fly off, the waves roll away and we depart.",
    "55": "\r\n我的白昼已经完了，我象一只泊在海滩上的小船，谛听着晚潮跳舞的乐声。\r\nMy day is done, and I am like a boat drawn on the beach, listening to the dance-music of the tide in the evening.",
    "56": "\r\n我们的生命是天赋的，我们惟有献出生命，才能得到生命。\r\nLife is given to us, we earn it by giving it.",
    "57": "\r\n当我们是大为谦卑的时候，便是我们最接近伟大的时候。\r\nWe come nearest to the great when we are great in humility.",
    "58": "\r\n麻雀看见孔雀负担着它的翎尾，替它担忧。\r\nThe sparrow is sorry for the peacock at the burden of its tail.",
    "59": "\r\n决不要害怕刹那－－永恒之声这样唱着。\r\nNever be afraid of the moments--thus sings the voice of the everlasting.",
    "60": "\r\n风于无路之中寻求最短之路，又突然地在“无何有之国”终之了它的追求。\r\nThe hurricane seeks the shortest road by the no-road, and suddenly ends its search in the Nowhere.",
    "61": "\r\n在我自己的杯中，饮了我的酒吧，朋友。\r\n一倒在别人的杯里，这酒的腾跳的泡沫便要消失了。\r\nTake my wine in my own cup, friend.\r\nIt loses its wreath of foam when poured into that of others.",
    "62": "\r\n“完全”为了对“不全”的爱，把自己装饰得美丽。\r\nThe perfect decks itself in beauty for the love of the Imperfect.",
    "63": "\r\n神对人说：“我医治你所以伤害你，爱你所以惩罚你。”\r\nGod says to man, \"I heal you therefore I hurt, love you therefore punish.\"",
    "64": "\r\n谢谢火焰给你光明，但是不要忘了那执灯的人，他是坚忍地站在黑暗当中呢。\r\nThank the flame for its light, but do not forget the lampholder standing in the shade with constancy of patience.",
    "65": "\r\n小草呀，你的足步虽小，但是你拥有你足下的土地。\r\nTiny grass, your steps are small, but you possess the earth under your tread.",
    "66": "\r\n幼花的蓓蕾开放了，它叫道：“亲爱的世界呀，请不要萎谢了。”\r\nThe infant flower opens its bud and cries, \"Dear World, please do not fade.\"",
    "67": "\r\n神对于那些大帝国会感到厌恶，却决不会厌恶那些小小的花朵。\r\nGod grows weary of great kingdoms, but never of little flowers.",
    "68": "\r\n错误经不起失败，但是真理却不怕失败。\r\nWrong cannot afford defeat but Right can.",
    "69": "\r\n瀑布歌唱道：“虽然渴者只要少许的水便够了，我却很快活地给与了我的全部的水。\r\nI give my whole water in joy, it is enough for the thirsty.",
    "70": "\r\n把那些花朵抛掷上去的那一阵子无休无止的狂欢大喜的劲儿，其源泉是在哪里呢？\r\nWhere is the fountain that throws up these flowers in a ceaseless outbreak of ecstasy?",
    "71": "\r\n樵夫的斧头，问树要斧柄。\r\n树便给了他。\r\nThe woodcutter's axe begged for its handle from the tree.\r\nThe tree gave it.",
    "72": "\r\n这寡独的黄昏，幕着雾与雨，我在我的心的孤寂里，感觉到它的叹息。\r\nIn my solitude of heart I feel the sigh of this widowed evening veiled with mist and rain.",
    "73": "\r\n贞操是从丰富的爱情中生出来的财富。\r\nChastity is a wealth that comes from abundance of love.",
    "74": "\r\n雾，象爱情一样，在山峰的心上游戏，生出种种美丽的变幻。\r\nThe mist, like love, plays upon the heart of the hills and brings out surprises of beauty.",
    "75": "\r\n我们把世界看错了，反说它欺骗我们。\r\nWe read the world wrong and say that it deceives us.",
    "76": "\r\n诗人－－飙风，正出经海洋森林，追求它自己的歌声。\r\nThe poet wind is out over the sea and the forest to seek his own voice.",
    "77": "\r\n每一个孩子出生时都带来信息说：神对人并未灰心失望。\r\nEvery child comes with the message that God is not yet discouraged of man.",
    "78": "\r\n绿草求她地上的伴侣。\r\n树木求他天空的寂寞。\r\nThe grass seeks her crowd in the earth.\r\nThe tree seeks his solitude of the sky.",
    "79": "\r\n人对他自己建筑起堤防来。\r\nMan barricades against himself.",
    "80": "\r\n我的朋友，你的语声飘荡在我的心里，象那海水的低吟声绕缭在静听着的松林之间。\r\nYour voice, my friend, wanders in my heart, like the muffled sound of the sea among these listening pines.",
    "81": "\r\n这个不可见的黑暗之火焰，以繁星为其火花的，到底是什么呢？\r\nWhat is this unseen flame of darkness whose sparks are the stars?",
    "82": "\r\n使生如夏花之绚烂，死如秋叶之静美。\r\nLet life be beautiful like summer flowers and death like autumn leaves.",
    "83": "\r\n那想做好人的，在门外敲着门；那爱人的看见门敞开着。\r\nHe who wants to do good knocks at the gate; he who loves finds the gate open.",
    "84": "\r\n在死的时候，众多和而为一；在生的时候，一化为众多。\r\n神死了的时候，宗教便将合而为一。\r\nIn death the many becomes one; in life the one becomes many.\r\nReligion will be one when God is dead.",
    "85": "\r\n艺术家是自然的情人，所以他是自然的奴隶，也是自然的主人。\r\nThe artist is the lover of Nature, therefore he is her slave and her master.",
    "86": "\r\n“你离我有多远呢，果实呀？”\r\n“我藏在你心里呢，花呀。”\r\nHow far are you from me, O Fruit?\r\nI am hidden in your heart, O Flower.",
    "87": "\r\n这个渴望是为了那个在黑夜里感觉得到，在大白天里却看不见的人。\r\nThis longing is for the one who is felt in the dark, but not seen in the day.",
    "88": "\r\n露珠对湖水说道；“你是在荷叶下面的大露珠，我是在荷叶上面的较小的露珠。”\r\nYou are the big drop of dew under the lotus leaf, I am the smaller one on its upper side,\" said the dewdrop to the lake.",
    "89": "\r\n刀鞘保护刀的锋利，它自己则满足于它的迟钝。\r\nThe scabbard is content to be dull when it protects the keenness of the sword.",
    "90": "\r\n在黑暗中，“一”视如一体；在光亮中，“一”便视如众多。\r\nIn darkness the One appears as uniform; in the light the One appears as manifold.",
    "91": "\r\n大地借助于绿草，显出她自己的殷勤好客。\r\nThe great earth makes herself hospitable with the help of the grass.",
    "92": "\r\n绿叶的生与死乃是旋风的急骤的旋转，它的更广大的旋转的圈子乃是在天上繁星之间徐缓的转动。\r\nThe birth and death of the leaves are the rapid whirls of the eddy whose wider circles move slowly among stars.",
    "93": "\r\n权势对世界说道：“你是我的。”\r\n世界便把权势囚禁在她的宝座下面。\r\n爱情对世界说道：“我是你的。”\r\n世界便给予爱情以在它屋内来往的自由。\r\nPower said to the world, \"You are mine.\"\r\nThe world kept it prisoner on her throne.\r\nLove said to the world, \"I am thine.\"\r\nThe world gave it the freedom of her house.",
    "94": "\r\n浓雾仿佛是大地的愿望。\r\n它藏起了太阳，而太阳原是她所呼求的。\r\nThe mist is like the earth's desire.\r\nIt hides the sun for whom she cries.",
    "95": "\r\n安静些吧，我的心，这些大树都是祈祷者呀。\r\nBe still, my heart, these great trees are prayers.",
    "96": "\r\n瞬刻的喧声，讥笑着永恒的音乐。\r\nThe noise of the moment scoffs at the music of the Eternal.",
    "97": "\r\n我想起了浮泛在生与爱与死的川流上的许多别的时代，以及这些时代之被遗忘，我便感觉到离开尘世的自由了。\r\nI think of other ages that floated upon the stream of life and love and death and are forgotten, and I feel the freedom of passing away.",
    "98": "\r\n我灵魂里的忧郁就是她的新婚的面纱。\r\n这面纱等候着在夜间卸去。\r\nThe sadness of my soul is her bride's veil.\r\nIt waits to be lifted in the night.",
    "99": "\r\n死之印记给生的钱币以价值，使它能够用生命来购买那真正的宝物。\r\nDeath's stamp gives value to the coin of life; making it possible to buy with life what is truly precious.",
    "100": "\r\n白云谦逊地站在天之一隅。\r\n晨光给它戴上霞彩。\r\nThe cloud stood humbly in a corner of the sky.\r\nThe morning crowned it with splendour.",
    "101": "\r\n尘土受到损辱，却以她的花朵来报答。\r\nThe dust receives insult and in return offers her flowers.",
    "102": "\r\n只管走过去，不必逗留着采了花朵来保存，因为一路上花朵自会继续开放的。\r\nDo not linger to gather flowers to keep them, but walk on, for flowers will keep themselves blooming all your way.",
    "103": "\r\n根是地下的枝。\r\n枝是空中的根。\r\nRoots are the branches down in the earth.\r\nBranches are roots in the air.",
    "104": "\r\n远远去了的夏之音乐，翱翔于秋间，寻求它的旧垒。\r\nThe music of the far-away summer flutters around the Autumn seeking its former nest.",
    "105": "\r\n不要从你自己的袋里掏出勋绩借给你的朋友，这是污辱他的。\r\nDo not insult your friend by lending him merits from your own pocket.",
    "106": "\r\n无名的日子的感触，攀缘在我的心上，正象那绿色的苔藓，攀\r\n缘在老树的周身。\r\nThe touch of the nameless days clings to my heart like mosses round the old tree.",
    "107": "\r\n回声嘲笑她的原声，以证明她是原声。\r\nThe echo mocks her origin to prove she is the original.",
    "108": "\r\n当富贵利达的人夸说他得到神的特别恩惠时，上帝却羞了。\r\nGod is ashamed when the prosperous boasts of His special favour.",
    "109": "\r\n我投射我自己的影子在我的路上，因为我有一盏还没有燃点起来的明灯。\r\nI cast my own shadow upon my path, because I have a lamp that has not been lighted.",
    "110": "\r\n人走进喧哗的群众里去，为的是要淹没他自己的沉默的呼号。\r\nMan goes into the noisy crowd to drown his own clamour of silence.",
    "111": "\r\n终止于衰竭是“死亡”，但“圆满”却终止于无穷。\r\nThat which ends in exhaustion is death, but the perfect ending is in the endless.",
    "112": "\r\n太阳只穿一件朴素的光衣，白云却披了灿烂的裙裾。\r\nThe sun has his simple rode of light. The clouds are decked with gorgeousness.",
    "113": "\r\n山峰如群儿之喧嚷，举起他们的双臂，想去捉天上的星星。\r\nThe hills are like shouts of children who raise their arms, trying to catch stars.",
    "114": "\r\n道路虽然拥挤，却是寂寞的，因为它是不被爱的。\r\nThe road is lonely in its crowd for it is not loved.",
    "115": "\r\n权势以它的恶行自夸，落下的黄叶与浮游的云片却在笑它。\r\nThe power that boasts of its mischiefs is laughed at by the yellow leaves that fall, and clouds that pass by.",
    "116": "\r\n今天大地在太阳光里向我营营哼鸣，象一个织着布的妇人，用一种已经被忘却的语言，哼着一些古代的歌曲。\r\nThe earth hums to me today in the sun, like a woman at her spinning, some ballad of the ancient time in a forgotten tongue.",
    "117": "\r\n绿草是无愧于它所生长的伟大世界的。\r\nThe grass-blade is worthy of the great world where it grows.",
    "118": "\r\n梦是一个一定要谈话的妻子。\r\n睡眠是一个默默忍受的丈夫。\r\nDream is a wife who must talk,\r\nSleep is a husband who silently suffers.",
    "119": "\r\n夜与逝去的日子接吻，轻轻地在他耳旁说道：“我是死，是你的母亲。我就要给你以新的生命。\r\nThe night kisses the fading day whispering to his ear, I am death, your mother. I am to give you fresh birth.",
    "120": "\r\n黑夜呀，我感觉到你的美了。你的美如一个可爱的妇人，当她把灯灭了的时候。\r\nI feel thy beauty, dark night, like that of the loved woman when she has put out the lamp.",
    "121": "\r\n我把在那些已逝去的世界上的繁荣带到我的世界上来。\r\nI carry in my world that flourishes the worlds that have failed.",
    "122": "\r\n亲爱的朋友呀，当我静听着海涛时，我好几次在暮色深沉的黄昏里，在这个海岸上，感到你的伟大思想的沉默了。\r\nDear friend, I feel the silence of your great thoughts of many a deepening eventide on this beach when I listen to these waves.",
    "123": "\r\n鸟以为把鱼举在空中是一种慈善的举动。\r\nThe bird thinks it is an act of kindness to give the fish a life in the air.",
    "124": "\r\n夜对太阳说道：“在月亮中，你送了你的情书给我。”\r\n“我已在绿草上留下了我的流着泪点的回答了。”\r\nIn the moon thou sendest thy love letters to me,\r\nI leave my answers in tears upon the grass.",
    "125": "\r\n伟人是一个天生的孩子，当他死时，他把他的伟大的孩提时代给了世界。\r\nThe great is a born child; when he dies he gives his great childhood\r\nto the world.",
    "126": "\r\n不是槌的打击，乃是水的载歌载舞，使鹅卵石臻于完美。\r\nNot hammer-strokes, but dance of the water sings the pebbles into perfection.",
    "127": "\r\n蜜蜂从花中啜蜜，离开时营营地道谢。\r\n浮华的蝴蝶却相信花是应该向它道谢的。\r\nBees sip honey from flowers and hum their thanks when they leave.\r\nThe gaudy butterfly is sure that the flowers owe thanks to him.",
    "128": "\r\n如果你不等待着要说出完全的真理，那末把真话说出来是很容易的。\r\nTo be outspoken is easy when you do not wait to speak the complete truth.",
    "129": "\r\n“可能”问“不可能”道：\r\n“你住在什么地方呢？”\r\n它回答道：“在那无能为力者的梦境里。”\r\nAsks the Possible to the Impossible,\r\nWhere is your dwelling-place?\r\nIn the dreams of the impotent, comes the answer.",
    "130": "\r\n如果你把所有的错误都关在门外时，真理也要被关在门外面了。\r\nIf you shut your door to all errors truth will be shut out.",
    "131": "\r\n我听见有些东西在我心的忧闷后面萧萧作响，－－我不能看见它们。\r\nI hear some rustle of things behind my sadness of heart,\r\n---I cannot see them.",
    "132": "\r\n闲暇在动作时便是工作。\r\n静止的海水荡动时便成波涛。\r\nLeisure in its activity is work.\r\nThe stillness of the sea stirs in waves.",
    "133": "\r\n绿叶恋爱时便成了花。\r\n花崇拜时便成了果实。\r\nThe leaf becomes flower when it loves.\r\nThe flower becomes fruit when it worships.",
    "134": "\r\n埋在地下的树根使树枝产生果实，却不要什么报酬。\r\nThe roots below the earth claim no rewards for making the branches fruitful.",
    "135": "\r\n阴雨的黄昏，风无休止地吹着。\r\n我看着摇曳的树枝，想念万物的伟大。\r\nThis rainy evening the wind is restless.\r\nI look at the swaying branches and ponder over the greatness of all things.",
    "136": "\r\n子夜的风雨，如一个巨大的孩子，在不合时宜的黑夜里醒来，开始游喜和喧闹。\r\nStorm of midnight, like a giant child awakened in the untimely dark, has begun to play and shout.",
    "137": "\r\n海呀，你这暴风雨的孤寂的新妇呀，你虽掀起波浪追随你的情人，但是无用呀。\r\nThou raisest thy waves vainly to follow thy lover, O sea, thou lonely bride of the storm.",
    "138": "\r\n文字对工作说道：“我惭愧我的空虚。”\r\n工作对文字说道：“当我看见你的时，我便知道我是怎样地贫乏了。”\r\nI am ashamed of my emptiness, said the Word to the Work.\r\nI know how poor I am when I see you, said the Work to the Word.",
    "139": "\r\n时间是变化的财富。时钟模仿它，却只有变化而无财富。\r\nTime is the wealth of change, but the clock in its parody makes it mere change and no wealth.",
    "140": "\r\n真理穿了衣裳，觉得事实太拘束了。\r\n在想象中，她却转动得很舒畅。\r\nTruth in her dress finds facts too tight.\r\nIn fiction she moves with ease.",
    "141": "\r\n当我到这里那里旅行着时，路呀，我厌倦你了；当是现在，当你引导我到各处去时我便爱上你，与你结婚了。\r\nWhen I travelled to here and to there, I was tired of thee, O Road, but now when thou leadest me to everywhere I am wedded to thee in love.",
    "142": "\r\n让我设想，在群星之中，有一颗星是指导着我的生命通过不可知的黑暗的。\r\nLet me think that there is one among those stars that guides my life through the dark unknown.",
    "143": "\r\n妇人，你用了你美丽的手指，触着我的什物，秩序便如音乐似的生出来了。\r\nWoman, with the grace of your fingers you touched my things and order came out like music.",
    "144": "\r\n一个忧郁的声音，筑巢于逝水似的年华中。\r\n它在夜里向我唱道：“我爱你。”\r\nOne sad voice has its nest among the ruins of the years.\r\nIt sings to me in the night, ---I loved you.",
    "145": "\r\n燃着的火，以它熊熊的光焰警告我不要走近它。\r\n把我从潜藏在灰中的余烬里救出来吧。\r\nThe flaming fire warns me off by its own glow.\r\nSave me from the dying embers hidden under ashes.",
    "146": "\r\n我有群星在天上，\r\n但是，唉，我屋里的小灯却没有点亮。\r\nI have my stars in the sky.\r\nBut oh for my little lamp unlit in my house.",
    "147": "\r\n死文字的尘土沾着你。\r\n用沉默去洗净你的灵魂吧。\r\nThe dust of the dead words clings to thee.\r\nWash thy soul with silence.",
    "148": "\r\n生命里留了许多罅隙，从中送来了死之忧郁的音乐。\r\nGaps are left in life through which comes the sad music of death.",
    "149": "\r\n世界已在早晨敞开了它的光明之心。\r\n出来吧，我的心，带着你的爱去与它相会。\r\nThe world has opened its heart of light in the morning.\r\nCome out, my heart, with thy love to meet it.",
    "150": "\r\n我的思想随着这些闪耀的绿叶而闪耀；我的心灵因了这日光的抚触而歌唱；\r\n我的生命因为偕了万物一同浮泛在空间的蔚蓝，时间的墨黑而感到欢快\r\nMy thoughts shimmer with these shimmering leaves and my heart sings with the touch of this sunlight; \r\nmy life is glad to be floating with all things into the blue of space, into the dark of time.",
    "151": "\r\n神的巨大的威权是在柔和的微（风思）里，而不在狂风暴雨之中。\r\nGod's great power is in the gentle breeze, not in the storm.",
    "152": "\r\n在梦中，一切事都散漫着，都压着我，但这不过是一个梦呀。但我醒来时，我便将觉得这些事都已聚集在你那里，我也便将自由了。\r\nThis is a dream in which things are all loose and they oppress.\r\nI shall find them gathered in thee when I awake and shall be free.",
    "153": "\r\n落日问道：“有谁继续我的职务呢？”\r\n瓦灯说道：“我要尽我所能地做去，我的主人。”\r\nWho is there to take up my duties? asked the setting sun.\r\nI shall do what I can, my Master, said the earthen lamp.",
    "154": "\r\n采着花瓣时，得不到花的美丽。\r\nBy plucking her petals you do not gather the beauty of the flower.",
    "155": "\r\n沉默蕴蓄着语声，正如鸟巢拥围着睡鸟。\r\nSilence will carry your voice like the nest that holds the sleeping birds.",
    "156": "\r\n大的不怕与小的同游。\r\n居中的却远而避之。\r\nThe Great walks with the Small without fear.\r\nThe Middling keeps aloof.",
    "157": "\r\n夜秘密地把花开放了，却让白日去领受谢词。\r\nThe night opens the flowers in secret and allows the day to get thanks.",
    "158": "\r\n权势认为牺牲者的痛苦是忘恩负义。\r\nPower takes as ingratitude the writhings of its victims.",
    "159": "\r\n当我们以我们的充实为乐时，那末，我们便能很快乐地跟我们的果实分手了。\r\nWhen we rejoice in our fulness, then we can part with our fruits with joy.",
    "160": "\r\n雨点吻着大地，微语道：“我们是你的思家的孩子，母亲，现在从天上回到你这里来了。”\r\nThe raindrops kissed the earth and whispered, --- We are thy homesick children, mother, come back to thee from the heaven.",
    "161": "\r\n蛛网好象要捉露点，却捉住了苍蝇。\r\nThe cobweb pretends to catch dewdrops and catches flies.",
    "162": "\r\n爱情呀，当你手里拿着点亮了的痛苦之灯走来时，我能够看见你的脸，而且以你为幸福。\r\nLove! When you come with the burning lamp of pain in your hand, I can see your face and know you as bliss.",
    "163": "\r\n萤火对天上的星说道：“学者说你的光明总有一天会消灭的。”\r\n天上的星不回答它。\r\nThe leaned say that your lights will one day be no more, said the firefly to the stars.\r\nThe stars made no answer.",
    "164": "\r\n在黄昏的微光里，有那清晨的鸟儿来到了我的沉默的鸟巢里。\r\nIn the dusk of the evening the bird of some early dawn comes to the nest of my silence.",
    "165": "\r\n思想掠过我的心上，如一群野鸭飞过天空。\r\n我听见它们鼓翼之声了。\r\nThoughts pass in my mind like flocks of lucks in the sky.\r\nI hear the voice of their wings.",
    "166": "\r\n沟洫总喜欢想：河流的存在，是专为它供给水流的。\r\nThe canal loves to think that rivers exist solely to supply it with water.",
    "167": "\r\n世界以它的痛苦同我接吻，而要求歌声做报酬。\r\nThe world has kissed my soul with its pain, asking for its return in songs.",
    "168": "\r\n压迫着我的，到底是我的想要外出的灵魂呢，还是那世界的灵魂，敲着我心的门，想要进来呢？\r\nThat which oppresses me, is it my soul trying to come out in the open, or the soul of the world knocking at my heart for its entrance?",
    "169": "\r\n思想以他自己的语言喂养它自己而成长起来了。\r\nThought feeds itself with its own words and grows.",
    "170": "\r\n我把我心之碗轻轻浸入这沉默之时刻中，它盛满了爱了。\r\nI have dipped the vessel of my heart into this silent hour; it has filled with love.",
    "171": "\r\n或者你在工作，或者你没有。\r\n当你不得不说：“让我们做些事吧”时，那末就要开始胡闹了。\r\nEither you have work or you have not.\r\nWhen you have to say, \"Let us do something\", then begins mischief.",
    "172": "\r\n向日葵羞于把无名的花朵看作它的同胞。\r\n太阳升上来了，向它微笑，说道：“你好么，我的宝贝儿？”\r\nThe sunflower blushed to own the nameless flower as her kin.\r\nThe sun rose and smiled on it, saying, \"Are you well, my darling?\"",
    "173": "\r\n“谁如命运似的催着我向前走呢？”\r\n“那是我自己，在身背后大跨步走着。”\r\nWho drives me forward like fate?\r\nThe Myself striding on my back.",
    "174": "\r\n云把水倒在河的水杯里，它们自己却藏在远山之中。\r\nThe clouds fill the watercups of the river, hiding themselves in the distant hills.",
    "175": "\r\n我一路走去，从我的水瓶中漏出水来。\r\n只剩下极少极少的水供我回家使用了。\r\nI spill water from my water jar as I walk on my way,\r\nVery little remains for my home.",
    "176": "\r\n杯中的水是光辉的；海中的水却是黑色的。\r\n小理可以用文字来说清楚，大理却只有沉末。\r\nThe water in a vessel is sparkling; the water in the sea is dark.\r\nThe small truth has words that are clear; the great truth has great silence.",
    "177": "\r\n你的微笑是你自己田园里的花，你的谈吐是你自己山上的松林的萧萧；但是你的心呀，却是那个女人，那个我们全都认识的女人。\r\nYour smile was the flowers of your own fields, your talk was the rustle of your own mountain pines, but your heart was the woman that we all know.",
    "178": "\r\n我把小小的礼物留给我所爱的人，－－大的礼物却留给一切的人。\r\nIt is the little things that I leave behind for my loved ones,\r\n---great things are for everyone.",
    "179": "\r\n妇人呀，你用泪海包绕着世界的心，正如大海包绕着大地。\r\nWoman, thou hast encircled the world’s heart with the depth of thy tears as the sea has the earth.",
    "180": "\r\n太阳以微笑向我问候。\r\n雨，他的忧闷的姐姐，向我的心谈话。\r\nThe sunshine greets me with a smile.\r\nThe rain, his sad sister, talks to my heart.",
    "181": "\r\n我的昼间之花，落下它那被遗忘的花瓣。\r\n在黄昏中，这花成熟为一颗记忆的金果。\r\nMy flower of the day dropped its petals forgotten.\r\nIn the evening it ripens into a golden fruit of memory.",
    "182": "\r\n我象那夜间之路，正静悄悄地谛听着记忆的足音。\r\nI am like the road in the night listening to the footfalls of its memories in silence.",
    "183": "\r\n黄昏的天空，在我看来，象一扇窗户，一盏灯火，灯火背后的一次等待。\r\nThe evening sky to me is like a window, and a lighted lamp, and a waiting behind it.",
    "184": "\r\n太急于做好事的人，反而找不到时间去做好人。\r\nHe who is too busy doing good finds no time to be good.",
    "185": "\r\n我是秋云，空空地不载着雨水，但在成熟的稻田中，可以看见我的充实。\r\nI am the autumn cloud, empty of rain, see my fullness in the field of ripened rice.",
    "186": "\r\n他们嫉妒，他们残杀，人反而称赞他们。\r\n然而上帝却害了羞，匆匆地把他的记忆埋藏在绿草下面。\r\nThey hated and killed and men praised them.\r\nBut God in shame hastens to hide its memory under the green grass.",
    "187": "\r\n脚趾乃是舍弃了其过去的手指。\r\nToes are the fingers that have forsaken their past.",
    "188": "\r\n黑暗向光明旅行，但是盲者却向死亡旅行。\r\nDarkness travels towards light, but blindness towards death.",
    "189": "\r\n小狗疑心大宇宙阴谋篡夺它的位置。\r\nThe pet dog suspects the universe for scheming to take its place.",
    "190": "\r\n静静地坐着吧，我的心，不要扬起你的尘土。\r\n让世界自己寻路向你走来。\r\nSit still, my heart, do not raise your dust.\r\nLet the world find its way to you.",
    "191": "\r\n弓在箭要射出之前，低声对箭说道：“你的自由就是我的自由。”\r\nThe bow whispers to the arrow before it speeds forth--Your freedom is mine.",
    "192": "\r\n妇人，在你的笑声里有着生命之泉的音乐。\r\nWoman, in your laughter you have the music of the fountain of life.",
    "193": "\r\n全是理智的心，恰如一柄全是锋刃的刀。\r\n它叫使用它的人手上流血。\r\nA mind all logic is like a knife all blade.\r\nIt makes the hand bleed that uses it.",
    "194": "\r\n神爱人间的灯光甚于他自己的大星。\r\nGod loves man's lamp lights better than his own great stars.",
    "195": "\r\n这世界乃是为美之音乐所驯服了的狂风骤雨的世界。\r\nThis world is the world of wild storms kept tame with the music of beauty.",
    "196": "\r\n晚霞向太阳说道：“我的心经了你的接吻，便似金的宝箱了。”\r\nMy heart is like the golden casket of thy kiss, cloud to the sun.",
    "197": "\r\n接触着，你许会杀害；远离着，你许会占有。\r\nBy touching you may kill, by keeping away you may possess.",
    "198": "\r\n蟋蟀的唧唧，夜雨的淅沥，从黑暗中传到我的耳边，好似我已逝的少年时代沙地来到我的梦境中。\r\nThe cricket's chirp and the patter of rain come to me through the dark, like the rustle of dreams from my past youth.",
    "199": "\r\n花朵向星辰落尽了的曙天叫道：“我的露点全失落了。”\r\nI have lost my dewdrop, lost all its stars.",
    "200": "\r\n燃烧着的木块，熊熊地生出火光，叫道：“这是我的花朵，我的死亡。”让世界自己寻路向你走来。\r\nThe burning log bursts in flame and cries, --- \"This is my flower, my death.\"",
    "201": "\r\n黄蜂认为邻蜂储蜜之巢太小。\r\n他的邻人要他去建筑一个更小的。\r\nThe wasp thinks that the honeyhive of the neighbouring bees is too small.\r\nHis neighbours ask him to build one still smaller.",
    "202": "\r\n河岸向河流说道：“我不能留住你的波浪。\r\n让我保存你的足印在我的心里吧。”\r\nI cannot keep your waves,\r\nLet me keep your footprints in my heart.",
    "203": "\r\n白日以这小小的地球的喧扰，淹没了整个宇宙的沉默。\r\nThe day, with the noise of this little earth, drowns the silence of all worlds.",
    "204": "\r\n歌声在天空中感到无限，图画在地上感到无限，诗呢，无论在空中，在地上都是如此。\r\n因为诗的词句含有能走动的意义与能飞翔的音乐。\r\nThe song feels the infinite in the air, the picture in the earth, the poem in the air and the earth;\r\nFor its words have meaning that walks and music that soars.",
    "205": "\r\n太阳在西方落下时，他的早晨的东方已静悄悄地站在他面前。\r\nWhen the sun goes down to the West, the East of his morning stands before him in silence.",
    "206": "\r\n让我不要错误地把自己放在我的世界里而使它反对我。\r\nLet me not put myself wrongly to my world and set it against me.",
    "207": "\r\n荣誉使我感到惭愧，因为我暗地里求着它。\r\nPraise shames me, for I secretly beg for it.",
    "208": "\r\n当我没有什么事做时，便让我不做什么事，不受骚扰地沉入安静深处吧，\r\n一如海水沉默时海边的暮色。\r\nLet my doing nothing when I have nothing to do become untroubled in its depth of peace like the evening in the seashore when the water is silent.",
    "209": "\r\n少女呀，你的纯朴，如湖水之碧，表现出你的真理之深邃。\r\nMaiden, your simplicity, like the blueness of the lake, reveals your depth of truth.",
    "210": "\r\n最好的东西不是独来的，\r\n它伴了所有的东西同来。\r\nThe best does not come alone.\r\nIt comes with the company of the all.",
    "211": "\r\n神的右手是慈爱的，但是他的左手却可怕。\r\nGod's right hand is gentle, but terrible is his left hand.",
    "212": "\r\n我的晚色从陌生的树木中走来，它用我的晓星所不懂得的语言说话。\r\nMy evening came among the alien trees and spoke in a language which my morning stars did not know.",
    "213": "\r\n夜之黑暗是一只口袋，迸出黎明的金光。\r\nNight's darkness is a bag that bursts with the gold of the dawn.",
    "214": "\r\n我们的欲望把彩虹的颜色借给那只不过是云雾的人生。\r\nOur desire lends the colours of the rainbow to the mere mists and vapours of life.",
    "215": "\r\n神等待着，要从人的手上把他自己的花朵作为礼物赢得回去。\r\nGod waits to win back his own flowers as gifts from man's hands.",
    "216": "\r\n我的忧思缠绕着我，要问我它自己的名字。\r\nMy sad thoughts tease me asking me their own names.",
    "217": "\r\n果的事业是尊贵的，花的事业是甜美的；但是让我做叶的事业吧，叶是谦逊地，专心地垂着绿荫的。\r\nThe service of the fruit is precious, the service of the flower is sweet, but let my service be the service of the leaves in its shade of humble devotion.",
    "218": "\r\n我的心向着阑珊的风张了帆，要到无论何处的荫凉之岛去。\r\nMy heart has spread its sails to the idle winds for the shadowy island of Anywhere.",
    "219": "\r\n独夫们是凶暴的，但人民是善良的。\r\nMen are cruel, but Man is kind.",
    "220": "\r\n把我当做你的杯吧，让我为了你，而且为了你的人而盛满水吧。\r\nMake me thy cup and let my fulness be for thee and for thine.",
    "221": "\r\n狂风暴雨象是在痛苦中的某个天神的哭声，因为他的爱情被大地所拒绝。\r\nThe storm is like the cry of some god in pain whose love the earth refuses.",
    "222": "\r\n世界不会流失，因为死亡并不是一个罅隙。\r\nThe world does not leak because death is not a crack.",
    "223": "\r\n生命因为付出了的爱情而更为富足。\r\nLife has become richer by the love that has been lost.",
    "224": "\r\n我的朋友，你伟大的心闪射出东方朝阳的光芒，正如黎明中的一个积雪的孤峰。\r\nMy friend, your great heart shone with the sunrise of the East like the snowy summit of a lonely hill in the dawn.",
    "225": "\r\n死之流泉，使生的止水跳跃。\r\nThe fountain of death makes the still water of life play.",
    "226": "\r\n那些有一切东西而没有您的人，我的上帝，在讥笑着那些没有别的东西而只有您的人呢。\r\nThose who have everything but thee, my God, laugh at those who have nothing but thyself.",
    "227": "\r\n生命的运动在它自己的音乐里得到它的休息。\r\nThe movement of life has its rest in its own music.",
    "228": "\r\n踢足只能从地上扬起尘土而不能得到收获。\r\nKicks only raise dust and not crops from the earth.",
    "229": "\r\n我们的名字，便是夜里海波上发出的光，痕迹也不留就抿灭了。\r\nOur names are the light that glows on the sea waves at night and then dies without leaving its signature.",
    "230": "\r\n让睁眼看着玫瑰花的人也看看它的刺。\r\nLet him only see the thorns who has eyes to see the rose.",
    "231": "\r\n鸟翼上系上了黄金，这鸟便永不能再在天上翱翔了。\r\nSet the bird's wings with gold and it will never again soar in the sky.",
    "232": "\r\n我们地方的荷花又在这陌生的水上开了花，放出同样的清香，只是名字换了。\r\nThe same lotus of our clime blooms here in the alien water with the same sweetness, under another name.",
    "233": "\r\n在心的远景里，那相隔的距离显得更广阔了。\r\nIn heart's perspective the distance looms large.",
    "234": "\r\n月儿把她的光明遍照在天上，却留着她的黑斑给她自己。\r\nThe moon has her light all over the sky, her dark spots to herself.",
    "235": "\r\n不要说：“这是早晨”，别用一个“昨天”的名词把它打发掉。你第一次看到它，把它当作还没有名字的新生孩子吧。\r\nDo not say, \"It is morning,\" and dismiss it with a mane of yesterday. See it for the first time as a new-born child that has no name.",
    "236": "\r\n青烟对天空夸口，灰烬对大地夸口，都以为它们是火的兄弟。\r\nSmoke boasts to the sky, and Ashes to the earth, that they are brothers to the fire.",
    "237": "\r\n雨点向茉莉花微语道：“把我永久地留在你的心里吧。”\r\n茉莉花叹息了一声，落在地上了。\r\nThe raindrop whispered to the jasmine, \"Keep me in your heart for ever.\"\r\nThe jasmine sighed, “Alas,\" and dropped to the ground.",
    "238": "\r\n腆怯的思想呀，不要怕我。\r\n我是一个诗人。\r\nTimid thoughts, do not be afraid of me.\r\nI am a poet.",
    "239": "\r\n我的心在朦胧的沉默里，似乎充满了蟋蟀的鸣声－－声音的灰暗的暮色。\r\nThe dim silence of my mind seems filled with crickets' chirp ---the grey twilight of sound.",
    "240": "\r\n爆竹呀，你对群星的侮蔑，又跟着你自己回到地上来了。\r\nRockets, your insult to the stars follows yourself back to the earth.",
    "241": "\r\n您曾经带领着我，穿过我的白天的拥挤不堪的旅程，而到达了我的黄昏的孤寂之境。\r\n在通宵的寂静里，我等待着它的意义。\r\nThou hast led me through my crowded travels of the day to my evening's loneliness.\r\nI wait for its meaning through the stillness of the night.",
    "242": "\r\n我们的生命就似渡过一个大海，我们都相聚在这个狭小的舟中。\r\n死时，我们便到了岸，各往各的世界去了。\r\nThis life is the crossing of a sea, where we meet in the same narrow ship.\r\nIn death we reach the shore and go to our different worlds.",
    "243": "\r\n真理之川从它的错误之沟渠中流过。\r\nThe stream of truth flows through its channels of mistakes.",
    "244": "\r\n今天我的心是在想家了，在想着那跨过时间之海的那一个甜蜜的时候。\r\nMy heart is homesick today for the one sweet hour across the sea of time.",
    "245": "\r\n鸟的歌声是曙光从大地反响过去的回声。\r\nThe bird-song is the echo of the morning light back from the earth.",
    "246": "\r\n晨光问毛茛道：“你是骄傲得不肯和我接吻么？”\r\nAre you too proud to kiss me?",
    "247": "\r\n小花问道：“我要怎样地对你唱，怎样地崇拜你呢？太阳呀？”\r\n太阳答道：“只要用你的纯洁的素朴的沉默。”\r\nHow may I sing to thee and worship, O Sun?\r\nBy the simple silence of thy purity,",
    "248": "\r\n当人是兽时，他比兽还坏。\r\nMan is worse than an animal when he is an animal.",
    "249": "\r\n黑云受光的接吻时便变成天上的花朵。\r\nDark clouds become heaven's flowers when kissed by light.",
    "250": "\r\n不要让刀锋讥笑它柄子的拙钝。\r\nLet not the sword-blade mock its handle for being blunt.",
    "251": "\r\n夜的沉默，如一个深深的灯盏，银河便是它燃着的灯光。\r\nThe night's silence, like a deep lamp, is burning with the light of its milky way.",
    "252": "\r\n死象大海的无限的歌声，日夜冲击着生命的光明岛的四周。\r\nAround the sunny island of Life swells day and night death's limitless song of the sea.",
    "253": "\r\n花瓣似的山峰在饮着日光，这山岂不象一朵花吗繝\r\nIs not this mountain like a flower, with its petals of hill, drinking the sunlight?",
    "254": "\r\n“真实”的含义被误解，轻重被倒置，那就成了“不真实”。\r\nThe real with its meaning read wrong and emphasis misplaced is the unreal.",
    "255": "\r\n我的心呀，从世界的流动找你的美吧，正如那小船得到风与水的优美似的。\r\nFind your beauty, my heart, from the world's movement, like the boat that has the grace of the wind and the water.",
    "256": "\r\n眼不能以视来骄人，却以它们的眼镜来骄人。\r\nThe eyes are not proud of their sight but of their eyeglasses.",
    "257": "\r\n我住在我的这个小小的世界里，生怕使它再缩小一丁点儿。把我抬举到您的世界里去吧，让我高高兴兴地失去我的一切的自由。\r\nI live in this little world of mine and am afraid to make it the least less. Life me into thy world and let me have the freedom gladly\r\nto lose my all.",
    "258": "\r\n虚伪永远不能凭借它生长在权力中而变成真实。\r\nThe false can never grow into truth by growing in power.",
    "259": "\r\n我的心，同着它的歌的拍拍舐岸的波浪，渴望着要抚爱这个阳光熙和的绿色世界。\r\nMy heart, with its lapping waves of son, longs to caress this green world of the sunny day.",
    "260": "\r\n道旁的草，爱那天上的星吧，你的梦境便可在花朵里实现了。\r\nWayside grass, love the star, then your dreams will come out in flowers.",
    "261": "\r\n让你的音乐如一柄利刃，直刺入市井喧扰的心中吧。\r\nLet your music, like a sword, pierce the noise of the market to its heart.",
    "262": "\r\n这树的颤动之叶，触动着我的心，象一个婴儿的手指。\r\nThe trembling leaves of this tree touch my heart like the fingers of an infant child.",
    "263": "\r\n小花睡在尘土里。\r\n它寻求蛱蝶走的道路。\r\nThe little flower lies in the dust.\r\nIt sought the path of the butterfly.",
    "264": "\r\n我是在道路纵横的世界上。\r\n夜来了。打开您的门吧，家之世界呵！\r\nI am in the world of the roads.\r\nThe night comes. Open thy gate, thou world of the home.",
    "265": "\r\n我已经唱过了您的白天的歌。\r\n在黄昏的时候，让我拿着您的灯走过风雨飘摇的道路吧。\r\nI have sung the songs of thy day.\r\nIn the evening let me carry thy lamp through the stormy path.",
    "266": "\r\n我不要求你进我的屋里。\r\n你到我无量的孤寂里来吧，我的爱人！\r\nI do not ask thee into the house.\r\nCome into my infinite loneliness, my Lover.",
    "267": "\r\n死亡隶属于生命，正与生一样。\r\n举足是走路，正如落足也是走路。\r\nDeath belongs to life as birth does.\r\nThe walk is in the raising of the foot as in the laying of it down.",
    "268": "\r\n我已经学会在花与阳光里微语的意义。－－再教我明白你在苦与死中所说的话吧。\r\nI have learnt the simple meaning of thy whispers in flowers and sunshine---teach me to know thy words in pain and death.",
    "269": "\r\n夜的花朵来晚了，当早晨吻着她时，她颤栗着，叹息了一声，萎落在地上了。\r\nThe night's flower was late when the morning kissed her, she shivered and sighed and dropped to the ground.",
    "270": "\r\n从万物的愁苦中，我听见了“永恒母亲”的呻吟。\r\nThrough the sadness of all things I hear the crooning of the Eternal Mother.",
    "271": "\r\n大地呀，我到你岸上时是一个陌生人，住在你屋内时是一个宾客，离开你\r\n的门时是一个朋友。\r\nI came to your shore as a stranger, I lived in your house as a guest, I leave your door as a friend, my earth.",
    "272": "\r\n当我去时，让我的思想到你那里来，如那夕阳的余光，映在沉默的星天的边上。\r\nLet my thoughts come to you, when I am gone, like the after glow of sunset at the margin of starry silence.",
    "273": "\r\n在我的心头燃点起那休憩的黄昏星吧，然后让黑夜向我微语着爱情。\r\nLight in my heart the evening star of rest and then let the night whisper to me of love.",
    "274": "\r\n我是一个在黑暗中的孩子。\r\n我从夜的被单里向您伸出我的双手，母亲。\r\nI am a child in the dark.\r\nI stretch my hands through the coverlet of night for thee, Mother.",
    "275": "\r\n白天的工作完了。把我的脸掩藏在您的臂间吧，母亲。\r\n让我入梦吧。\r\nThe day of work is done. Hide my face in your arms, Mother.\r\nLet me dream.",
    "276": "\r\n集会时的灯光，点了很久，会散时，灯便立刻灭了。\r\nThe lamp of meeting burns long; it goes out in a moment at the parting.",
    "277": "\r\n当我死时，世界呀，请在你的沉默中，替我留着“我已经爱过了”这句话吧。\r\nOne word keep for me in thy silence, O World, when I am dead, I have loved.",
    "278": "\r\n我们在热爱世界时便生活在这世界上。\r\nWe live in this world when we love it.",
    "279": "\r\n让死者有那不朽的名，但让生者有那不朽的爱。\r\nLet the dead have the immortality of fame, but the living the immortality of love.",
    "280": "\r\n我看见你，象那半醒的婴孩在黎明的微光里看见他的母亲，于是微笑而又睡去了。\r\nI have seen thee as the half-awakened child sees his mother in the dusk of the dawn and then smiles and sleeps again.",
    "281": "\r\n我将死了又死，以明白生是无穷无尽的。\r\nI shall die again and again to know that life is inexhaustible.",
    "282": "\r\n当我和拥挤的人群一同在路上走过时，我看见您从阳台上送过来的微笑，我歌唱着，忘却了所有的喧哗。\r\nWhile I was passing with the crowd in the road I saw thy smile from the balcony and I sang and forgot all noise.",
    "283": "\r\n爱就是充实了的生命，正如盛满了酒的酒杯。\r\nLove is life in its fulness like the cup with its wine.",
    "284": "\r\n他们点了他们自己的灯，在他们的寺院内，吟唱他们自己的话语。\r\n但是小鸟们却在你的晨光中，唱着你的名字，－－因为你的名字便是快乐。\r\nThey light their own lamps and sing their own words in their temples.\r\nBut the birds sing thy name in thine own morning light, --- for thy name is joy.",
    "285": "\r\n领我到您的沉寂的中心，使我的心充满了歌吧。\r\nLead me in the centre of thy silence to fill my heart with songs.",
    "286": "\r\n让那些选择了他们自己的焰火咝咝的世界的，就生活在那里吧。\r\n我的心渴望着您的繁星，我的上帝。\r\nLet them live who choose in their own hissing world of fireworks.\r\nMy heart long s for thy stars, my God.",
    "287": "\r\n爱的痛苦环绕着我的一生，象汹涌的大海似地唱；而爱的快乐却象鸟儿们在话林里似地唱着。\r\nLove's pain sang round my life like the unplumbed sea, and love's joy sang like birds in its flowering groves.",
    "288": "\r\n假如您愿意，您就熄了灯吧。\r\n我将明白您的黑暗，而且将喜爱它。\r\nPut out the lamp when thou wishest.\r\nI shall know thy darkness and shall love it.",
    "289": "\r\n当我在那日子的终了，站在您的面前时，您将看见我的伤疤，而知道我有我的许多创伤，但也有我的医治的法儿。\r\nWhen I stand before thee at the day s end thou shalt see my scars and know that I had my wounds and also my healing.",
    "290": "\r\n总有一天，我要在别的世界的晨光里对你唱道：“我以前在地球的光里，在人的爱里，已经见过你了。”\r\nSome day I shall sing to thee in the sunrise of some other world, I have seen thee before in the light of the earth, in the love of man.",
    "291": "\r\n从别的日子里飘浮道我的生命里的云，不再落下雨点或引起风暴了，却只给予我的夕阳的天空以色彩。\r\nClouds come floating into my life from other days no longer to shed rain or usher storm but to give colour to my sunset sky.",
    "292": "\r\n真理引起了反对它自己的狂风骤雨，那场风雨吹散了真理的广播的种子。\r\nTruth raises against itself the storm that scatters its seeds broadcast.",
    "293": "\r\n昨夜的风雨给今日的早晨戴上了金色的和平。\r\nThe storm of the last night has crowned this morning with golden peace.",
    "294": "\r\n真理仿佛带了它的结论而来；而那结论却产生了它的第二个。\r\nTruth seems to come with its final word; and the final word gives\r\nbirth to its next.",
    "295": "\r\n他是有福的，因为他的名望并没有比他的真实更光亮。\r\nBlessed is he whose fame does not outshine his truth.",
    "296": "\r\n您的名字的甜蜜充溢着我的心，而我忘掉了我自己的，－－就象您的早晨的太阳升起时，那大雾便消失了。\r\nSweetness of thy name fills my heart when I forget mine---like thy morning sun when the mist is melted.",
    "297": "\r\n静悄悄的黑夜具有母亲的美丽，而吵闹的白天具有孩子的美丽。\r\nThe silent night has the beauty of the mother and the clamorous day of the child.",
    "298": "\r\n但人微笑时，世界爱了他；但他大笑时世界便怕他了。\r\nThe world loved man when he smiled. The world became afraid of him when he laughed.",
    "299": "\r\n神等待着人在智慧中重新获得童年。\r\nGod waits for man to regain his childhood in wisdom.",
    "300": "\r\n让我感到这个世界乃是您的爱的成形吧，那末，我的爱也将帮助着它。\r\nLet me feel this world as thy love taking form, then my love will help it.",
    "301": "\r\n您的阳光对着我的心头的冬天微笑，从来不怀疑它的春天的花朵。\r\nThy sunshine smiles upon the winter days of my heart, never doubting of its spring flowers.",
    "302": "\r\n神在他的爱里吻着“有涯”，而人却吻着“无涯”。\r\nGod kisses the finite in his love and man the infinite.",
    "303": "\r\n您越过不毛之年的沙漠而到达了圆满的时刻。\r\nThou crossest desert lands of barren years to reach the moment of fulfilment.",
    "304": "\r\n神的静默使人的思想成熟而为语言。\r\nGod's silence ripens man's thoughts into speech.",
    "305": "\r\n“永恒的旅客”呀，你可以在我的歌众找到你的足迹。\r\nThou wilt find, Eternal Traveller, marks of thy footsteps across my songs.",
    "306": "\r\n让我不至羞辱您吧，父亲，您在您的孩子们身上显出您的光荣。\r\nLet me not shame thee, Father, who displayest thy glory in thy children.",
    "307": "\r\n这一天是不快活的。光在蹙额的云下，如一个被责打的儿童，灰白的脸上留着泪痕；风又号叫着，似一个受伤的世界的哭声。但是我知道，我正跋涉着去会我的朋友。\r\nCheerless is the day, the light under frowning clouds is like a punished child with traces of tears on its pale cheeks, and the cry of the wind is like the cry of a wounded world. But I know I am travelling to meet my Friend.",
    "308": "\r\n今天晚上棕榈叶在嚓嚓地作响，海上有大浪，满月呵，就象世界在心脉悸跳。从什么不可知的天空，您在您的沉默里带来了爱的痛苦的秘密？\r\nTonight there is a stir among the palm leaves, a swell in the sea, Full Moon, like the heart throb of the world. From what unknown sky hast thou carried in thy silence the aching secret of love?",
    "309": "\r\n我梦见一颗星，一个光明岛屿，我将在那里出生。在它快速的闲暇深处，我的生命将成熟它的事业，象阳光下的稻田。\r\nI dream of a star, an island of light, where I shall be born and in the depth of its quickening leisure my life will ripen its works like the rice-field in the autumn sun.",
    "310": "\r\n雨中的湿土的气息，就响从渺小的无声的群众那里来的一阵巨大的赞美歌声。\r\nThe smell of the wet earth in the rain rises like a great chant of praise from the voiceless multitude of the insignificant.",
    "311": "\r\n说爱情会失去的那句话，乃是我们不能够当作真理来接受的一个事实。\r\nThat love can ever lose is a fact that we cannot accept as truth.",
    "312": "\r\n我们将有一天会明白，死永远不能够夺去我们的灵魂所获得的东西。因为她所获得的，和她自己是一体。\r\nWe shall know some day that death can never rob us of that which our soul has gained, for her gains are one with herself.",
    "313": "\r\n神在我的黄昏的微光中，带着花到我这里来。这些花都是我过去的，在他的花篮中还保存得很新鲜。\r\nGod comes to me in the dusk of my evening with the flowers from my past kept fresh in his basket.",
    "314": "\r\n主呀，当我的生之琴弦都已调得谐和时，你的手的一弹一奏，都可以发出爱的乐声来。\r\nWhen all the strings of my life will be tuned, my Master, then at every touch of thine will come out the music of love.",
    "315": "\r\n让我真真实实地活着吧，我的上帝。这样，死对于我也就成了真实的了。\r\nLet me live truly, my Lord, so that death to me become true.",
    "316": "\r\n人类的历史在很忍耐地等待着被侮辱者的胜利。\r\nMan's history is waiting in patience for the triumph of the insulted man.",
    "317": "\r\n我这一刻感到你的眼光正落在我的心上，象那早晨阳光中的沉默落在已收获的孤寂的田野上一样。\r\nI feel thy gaze upon my heart this moment like the sunny silence of the morning upon the lonely field whose harvest is over.",
    "318": "\r\n在这喧哗的波涛起伏的海中，我渴望着咏歌之鸟。\r\nI long for the Island of Songs across this heaving Sea of Shouts.",
    "319": "\r\n夜的序曲是开始于夕阳西下的音乐，开始于它对难以形容的黑暗所作的庄严的赞歌。\r\nThe prelude of the night is commenced in the music of the sunset, in its solemn hymn to the ineffable dark.",
    "320": "\r\n我攀登上高峰，发现在名誉的荒芜不毛的高处，简直找不到一个遮身之地。\r\n我的引导者呵，领导着我在光明逝去之前，进到沉静的山谷里去吧。在那里，一生的收获将会成熟为黄金的智慧。\r\nI have scaled the peak and found no shelter in fame's bleak and barren height. Lead me, my Guide, before the light fades, into the valley of quiet where life's harvest mellows into golden wisdom.",
    "321": "\r\n在这个黄昏的朦胧里，好些东西看来都仿佛是幻象一般－－尖塔的底层在黑暗里消失了，树顶象是墨水的模糊的斑点似的。我将等待着黎明，而当我醒来的时候，就会看到在光明里的您的城市。\r\nThings look phantastic in this dimness of the dusk---the spires whose bases are lost in the dark and tree tops like blots of ink. I shall wait for the morning and wake up to see thy city in the light.",
    "322": "\r\n我曾经受苦过，曾经失望过，曾经体会过“死亡”，于是我以我在这伟大的世界里为乐。\r\nI have suffered and despaired and known death and I am glad that I am in this great world.",
    "323": "\r\n在我的一生里，也有贫乏和沉默的地域；它们是我忙碌的日子得到日光与空气的几片空旷之地。\r\nThere are tracts in my life that are bare and silent. They are the open spaces where my busy days had their light and air.",
    "324": "\r\n我的未完成的过去，从后边缠绕到我身上，使我难于死去。请从它那里释放了我吧。\r\nRelease me from my unfulfilled past clinging to me from behind making death difficult.",
    "325": "\r\n“我相信你的爱。”让这句话做我的最后的话。\r\nLet this be my last word, that I trust thy love.\r\n"
  }


var chapters = stray_birds_json
var length = Object.keys(chapters).length;

var random = function (max) {
  return Math.ceil(Math.random() * max);
}

var random_chapter = function (init) {
  var thisIdx = init <= length ? init : random(length);
  var thisChapter = chapters[thisIdx];
  return {
    idx: thisIdx,
    content: thisChapter
  };
}

if (window) {
  window.stray_bird = random_chapter;
}
